########################################################
###common
########################################################
app:
  filesever:
    host: localhost
    path: /tmp
    thumbPath: /tmp/testUpload/image
########################################################
### static resources and upload load file
########################################################
base_assets_url: http://${app.filesever.host}/${spring.application.name}/assets/
base_assets_upload_path: ${app.filesever.path}/${spring.application.name}/upload/
base_assets_upload_url: http://${app.filesever.host}/${spring.application.name}/upload/
base_thumb_path: ${app.filesever.thumbPath}/${spring.application.name}/
########################################################
### 文档生成地址
########################################################
document:
  project-path: qiuqiu-admin
########################################################
### LOG
########################################################
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: INFO
    com.php25: INFO
    org.springframework.security: INFO
  file:
    name: logs/qiuqiu-admin.log
spring:
  ########################################################
  ### servlet
  ########################################################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    redis:
      repositories:
        enabled: false
########################################################
### 服务器运行时信息
########################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    redis:
      enabled: false
  server:
    port: 9091
  metrics:
    tags:
      application: ${spring.application.name}
