########################################################
###common
########################################################
jasypt:
  encryptor:
    ## 不安全 生产用 -Djasypt.encryptor.password=123456 方式
    password: '@WSXcft6#EDCvgy7'
app:
  db:
    ip: localhost
    port: 33306
    username: ENC(DySsEJn1LgKl6VqxdP7mTw==)
    password: ENC(znfy5SdaY3e0hXjTpZQv1w==)
    name: test
  filesever:
    host: localhost
    path: /tmp
    thumbPath: /tmp/testUpload/image
  redis:
    host: localhost
    port: 36379
    password: ENC(zGb6Ots9lRMd7RLIy6w12A==)
    database: 0
  rabbitmq:
    ip: localhost
    port: 5672
    username: ENC(Esk0at/quBKVrWD6PKHwAg==)
    password: ENC(GqHPMo3jAyV25ZAv5Zejnw==)
    virtualHost: /
########################################################
### static resources and upload load file
########################################################
base_assets_url: http://${app.filesever.host}/${spring.application.name}/assets/
base_assets_upload_path: ${app.filesever.path}/${spring.application.name}/upload/
base_assets_upload_url: http://${app.filesever.host}/${spring.application.name}/upload/
base_thumb_path: ${app.filesever.thumbPath}/${spring.application.name}/
########################################################
### 文档生成地址
########################################################
document:
  project-path: qiuqiu-admin
########################################################
### LOG
########################################################
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: INFO
    com.php25: INFO
    org.springframework.security: INFO
  file:
    name: /tmp/logs/qiuqiu-admin.log
spring:
  ########################################################
  ###datasource
  ########################################################
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.db.ip}:${app.db.port}/${app.db.name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${app.db.username}
    password: ${app.db.password}
    minIdle: 1
    connectionTimeout: 30000
    idleTimeout: 300000
    maxLifetime: 1800000
    maximumPoolSize: 15
    poolName: hikariDataSource
  ########################################################
  ### redis
  ########################################################
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port}
    database: ${app.redis.database}
    #password: ${app.redis.password}
    ssl: false
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5s
        min-idle: 0
    timeout: 5s
  ########################################################
  ### rabbitmq
  ########################################################
  rabbitmq:
    addresses: ${app.rabbitmq.ip}
    port: ${app.rabbitmq.port}
    username: ${app.rabbitmq.username}
    password: ${app.rabbitmq.password}
    virtual-host: ${app.rabbitmq.virtualHost}
  ########################################################
  ### servlet
  ########################################################
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
########################################################
### 服务器运行时信息
########################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9091
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
server:
  port: 8081
  servlet:
    context-path: /qiuqiu_admin
  id: ${random.uuid}
ws.enable: true
