###############################################
## common配置
###############################################
spring:
  profiles:
    active: local
  application:
    name: wx-company-admin
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/*
  webflux:
    static-path-pattern: /static/*
  data:
    redis:
      repositories:
        enabled: false
server:
  port: 8081
  servlet:
    context-path: /wxadmin
springfox:
  documentation:
    swagger-ui:
      enabled: false