apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qiuqiu-admin
  name: qiuqiu-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qiuqiu-admin
  strategy: {}
  template:
    metadata:
      labels:
        app: qiuqiu-admin
    spec:
      containers:
      - image: penghuiping/qiuqiu-admin
        name: qiuqiu-admin
        resources:
          requests:
            memory: 256M #内存256M
            cpu: 1000m #1个cpu
          limits:
            memory: 2048M
            cpu: 2000m
        livenessProbe: ## 健康检查，重启可以解决
          initialDelaySeconds: 60 #第一次健康检查的时间，需要晚于容器启动时间
          httpGet:
            port: 9091
            path: /actuator/health
#            path: /actuator/health/liveness
        readinessProbe: ## 启动以后，什么时候容器准备好可以处理外部请求
          httpGet:
            port: 9091
            path: /actuator/health
#            path: /actuator/health/readiness

