apiVersion: v1
kind: Service
metadata:
  labels:
    app: qiuqiu-admin
  name: qiuqiu-admin
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: 9091-9091
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: qiuqiu-admin
  type: ClusterIP
status:
  loadBalancer: {}

