apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: qiuqiu-admin
  name: qiuqiu-admin
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: qiuqiu-admin
  type: ClusterIP
status:
  loadBalancer: {}

