apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: penghuiping/qiuqiu-admin
    jib:
      args: ['-DskipTests']

deploy:
  kustomize:
    paths:
    - kustomize/base

profiles:
  - name: test
    deploy:
      kustomize:
        paths:
        - kustomize/test
