apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: penghuiping/qiuqiu-admin
      jib:
        args: ['-DskipTests']


deploy:
  kustomize:
    path: kustomize/base

profiles:
  - name: dev
    deploy:
      kustomize:
        path: kustomize/dev
