version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
       - 33306:3306
    volumes:
      - "./data/mysql/volume:/var/lib/mysql"
    command: mysqld -uroot --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    image: redis:5.0.4-alpine
    ports:
      - 36379:6379
    volumes:
      - "./data/redis/data:/data"
  rabbitmq:
    image: rabbitmq:3.7.17-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana/grafana.ini:/etc/grafana/grafana.ini"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
      - JAVA_OPTS=-Xms1g -Xmx1g -XX:+ExitOnOutOfMemoryError
    ports:
      - 9411:9411
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:5.6
    environment:
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "discovery.type=single-node"
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
  # bin/elasticsearch-reset-password -u elastic
  # bin/elasticsearch-create-enrollment-token -s kibana
  kibana:
    image: kibana:5.6
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  logstash:
    image: logstash:5.6
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./data/logstash/conf.d:/etc/logstash/conf.d
      - ./data/logstash/logst:/tmp
    depends_on:
      - elasticsearch
    ports:
      - "7001-7005:7001-7005"
      - "4560:4560"
      - "9600:9600"
  app:
    image: penghuiping/qiuqiu-admin:latest
    ports:
      - "8081:8081"
      - "9091:9091"
